import math
a = float(input("Enter the first number: "))
b = float(input("Enter the second number: "))
print(f"\nThe sum of {a} and {b} is {a+b}")
print(f"The difference when {b} is subtracted from {a} is {a-b}")
print(f"The product of {a} and {b} is {a*b}")
print(f"The quotient when {a} is divided by {b} is {a/b}")
print(f"The remainder when {a} is divided by {b} is {a%b}")
print(f"The result of log10{a} is {math.log10(a)}")
print(f"The result of {a}^{b} is {a**b}")
